# Generated by Django 6.0.5 on 2026-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('ptype', models.CharField()),
                ('p_mgf', models.DateField()),
                ('p_exp', models.DateField()),
            ],
        ),
    ]
